controller_list:
  - name: fake_hand_left_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_left_finger_joint1
  - name: fake_hand_right_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_right_finger_left_joint
      - panda_right_finger_right_joint
  - name: fake_hand_top_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_top_finger_left_joint
      - panda_top_finger_right_joint
  - name: fake_hand_triple_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_left_finger_joint1
      - panda_right_finger_left_joint
      - panda_right_finger_right_joint
      - panda_top_finger_left_joint
      - panda_top_finger_right_joint
  - name: fake_panda_left_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_left_joint1
      - panda_left_joint2
      - panda_left_joint3
      - panda_left_joint4
      - panda_left_joint5
      - panda_left_joint6
      - panda_left_joint7
  - name: fake_panda_right_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_right_joint1
      - panda_right_joint2
      - panda_right_joint3
      - panda_right_joint4
      - panda_right_joint5
      - panda_right_joint6
      - panda_right_joint7
  - name: fake_panda_top_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_top_joint1
      - panda_top_joint2
      - panda_top_joint3
      - panda_top_joint4
      - panda_top_joint5
      - panda_top_joint6
      - panda_top_joint7
  - name: fake_panda_triple_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_left_joint1
      - panda_left_joint2
      - panda_left_joint3
      - panda_left_joint4
      - panda_left_joint5
      - panda_left_joint6
      - panda_left_joint7
      - panda_right_joint1
      - panda_right_joint2
      - panda_right_joint3
      - panda_right_joint4
      - panda_right_joint5
      - panda_right_joint6
      - panda_right_joint7
      - panda_top_joint1
      - panda_top_joint2
      - panda_top_joint3
      - panda_top_joint4
      - panda_top_joint5
      - panda_top_joint6
      - panda_top_joint7
initial:  # Define initial robot poses per group
  - group: panda_left
    pose: init_left
  - group: panda_right
    pose: init_right
  - group: panda_top
    pose: init_top